server:
  port: 8081

spring:
  datasource:
    username: root
    password: Sxq599635
    url: jdbc:mysql://127.0.0.1:3306/stockdata?characterEncoding=utf-8&serverTimeZone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

